# Dependencies

In [83]:
import numpy as np
import random

# Using Arrays

In [2]:
arr_1d = np.array([1,2,3,4])
type(arr_1d)

numpy.ndarray

In [3]:
arr_1d.ndim         # The dimension of the array

1

In [4]:
arr_2D = np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12]])
arr_2D.size             # No. of elements in the array

12

In [5]:
arr_2D.shape            # (row, column)

(3, 4)

In [6]:
arr_2D.dtype        # to check data type

dtype('int32')

In [7]:
np.ones((3,4))      # creating 3 rows 4 cloumn of array conraining all 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros(
    (3,4),
    dtype = bool,
 )

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# Function

### Arange():

In [9]:
ar_1d = np.arange(1,13)
# ar_1d = np.arange(0,16,2)

In [10]:
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Linspace()

In [11]:
np.linspace(1,10,4)         

array([ 1.,  4.,  7., 10.])

### Reshape()

In [12]:
ar_1d.reshape(3,4)  # convert a array to another dimension

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
ar_3d = ar_1d.reshape(3,2,2)            # converting ot 3 Dimensions
ar_3d 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### Ravel()

In [14]:
ar_3d.ravel()     #makes a multi dimensional array into  1 dimensional

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Traspose()

In [15]:
ar_3d.transpose()

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

# Mathamatical Operation

In [16]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

In [17]:
print(arr1)
print("***************")
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***************
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [19]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# arr1 * arr2
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
# arr1 @ arr2             # Matrix Product
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [23]:
# arr1.max()          # To get the Max value
arr1.argmax()          # To get index of the Max  value

8

In [24]:
arr1.max(axis = 1)      # One is Row. max vlue in Row
arr1.max(axis = 0)      # zero is Column. max vlue in column

array([7, 8, 9])

In [25]:
arr1.min()
# arr1.argmin()                 # index of the min value

1

In [26]:
np.sum(arr1)        # add all the element in an array

45

In [27]:
np.sum(arr1, axis= 0)       # Adds the column. take 1 to add rows

array([12, 15, 18])

In [28]:
np.mean(arr1)

5.0

In [29]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [30]:
np.std(arr1)            # Standard deviation

2.581988897471611

In [31]:
np.exp(arr1)        

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [32]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [33]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# Array Slicing

In [36]:
mx = np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [40]:
mx[0] # To get the entire row

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [49]:
mx[1:4, 1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

# Array Conctination And Spliting

In [57]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [59]:
np.concatenate((arr1, arr2))            #column wise concatination

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [61]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [62]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [63]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [ ]:
np.split(arr1,2)

list

In [70]:
np.split( arr1, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [74]:
a1 =np.arange(0,7)
np.split(a1, [1,5])

[array([0]), array([1, 2, 3, 4]), array([5, 6])]

# Random Sampling 

In [84]:
np.random.random(1)

array([0.27614344])

In [85]:
np.random.random((3,3))

array([[0.53319808, 0.90827875, 0.13034384],
       [0.36484569, 0.74841312, 0.40925407],
       [0.44252394, 0.77099656, 0.41166169]])

In [99]:
np.random.randint(1,10 , (4,4))

array([[7, 1, 3, 9],
       [3, 4, 9, 3],
       [4, 9, 4, 5],
       [7, 6, 1, 8]])

In [100]:
np.random.randint(1,15,(2,4,4))

array([[[ 5,  3, 10,  6],
        [ 8,  7,  3, 12],
        [10, 11,  3, 11],
        [ 1,  5,  9,  6]],

       [[11, 13, 12,  9],
        [10,  4,  6,  6],
        [10,  3,  9, 10],
        [ 2, 13,  7,  7]]])

In [110]:
np.random.seed(11)
np.random.randint(1,15,(2,4,4))

array([[[10,  1, 12,  2],
        [ 8, 14, 13,  2],
        [ 8,  3,  9, 14],
        [13,  1, 14,  1]],

       [[14, 13, 14,  5],
        [ 3, 13,  2, 11],
        [ 6,  6,  8,  5],
        [ 2, 12,  9,  9]]])

In [115]:
np.random.rand(3,3)
np.random.randn(3,3)

array([[-0.61694826, -0.33191848,  0.31311598],
       [-1.01437938, -1.2548642 , -1.93803823],
       [-2.19310753,  1.0299373 ,  0.73815451]])

In [125]:
x = [1,2,3,4]
np.random.choice(x)

1

In [132]:
np.random.permutation(x)        #Shuffles the list

array([1, 2, 3, 4])

# String Opration, Comparasion and information

In [133]:
player_name = 'Arlechinno'
action = "Got a kill"

In [135]:
np.char.add(player_name,action)

array('ArlechinnoGot a kill', dtype='<U20')

In [138]:
np.char.lower(player_name)

array('arlechinno', dtype='<U10')

In [139]:
np.char.upper(action)

array('GOT A KILL', dtype='<U10')

In [143]:
np.char.center(action, 20,fillchar='*')

array('*****Got a kill*****', dtype='<U20')

In [145]:
np.char.split(action)

array(list(['Got', 'a', 'kill']), dtype=object)

In [149]:
np.char.splitlines("Hello there my name is not \nWorld")

array(list(['Hello there my name is not ', 'World']), dtype=object)

In [151]:
np.char.join([':'],player_name)

array(['A:r:l:e:c:h:i:n:n:o'], dtype='<U19')

In [153]:
np.char.replace(action,"kill","double kill")

array('Got a double kill', dtype='<U17')

In [155]:
np.char.equal(player_name, action)

array(False)

In [158]:
np.char.count(player_name,'n')

array(2)

In [160]:
np.char.find(action, 'a')

array(4)